# Generated by Django 3.0.4 on 2020-05-03 20:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mtmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateField(verbose_name='Climbed date')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Position')),
            ],
        ),
    ]
