# Generated by Django 3.0.4 on 2020-05-04 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mtmap',
            old_name='geom',
            new_name='Mtposition',
        ),
    ]
