# Generated by Django 3.0.4 on 2020-05-04 18:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20200504_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtmap',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='mountain/'),
            preserve_default=False,
        ),
    ]
