# Generated by Django 3.1 on 2020-08-13 07:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_mtmap_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPXsave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(verbose_name='Bike ride date')),
                ('gpx_file', models.FileField(upload_to='gpx_files/')),
            ],
        ),
        migrations.CreateModel(
            name='GPXtrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='Description')),
                ('track', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('gpx_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.gpxsave')),
            ],
        ),
    ]
