# Generated by Django 3.1 on 2020-08-13 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_gpxsave_gpxtrack'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GPXtrack',
        ),
    ]
