# Generated by Django 3.1 on 2020-08-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_delete_gpxtrack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mtmap',
            name='photo',
        ),
        migrations.AddField(
            model_name='mtmap',
            name='photo1',
            field=models.ImageField(blank=True, upload_to='mountain/'),
        ),
        migrations.AddField(
            model_name='mtmap',
            name='photo2',
            field=models.ImageField(blank=True, upload_to='mountain/'),
        ),
        migrations.AddField(
            model_name='mtmap',
            name='photo3',
            field=models.ImageField(blank=True, upload_to='mountain/'),
        ),
        migrations.AddField(
            model_name='mtmap',
            name='photo4',
            field=models.ImageField(blank=True, upload_to='mountain/'),
        ),
        migrations.AddField(
            model_name='mtmap',
            name='photo5',
            field=models.ImageField(blank=True, upload_to='mountain/'),
        ),
    ]
