# Generated by Django 3.0.4 on 2020-03-12 15:08

from django.db import migrations, models
import django.utils.timezone
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('contents', markdownx.models.MarkdownxField(help_text='To Write with Markdown format', verbose_name='Contents')),
                ('category', models.CharField(max_length=255, verbose_name='Category')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='time')),
                ('tags', models.ManyToManyField(related_name='posts_tags', to='blog.Tag')),
            ],
        ),
    ]
