# Generated by Django 3.0.4 on 2020-03-16 20:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='time',
        ),
        migrations.AddField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Createded Time'),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='flag of publication'),
        ),
        migrations.AddField(
            model_name='post',
            name='published_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pblished Time'),
        ),
    ]
